### ISSUE TITLE
Split the report in "general" and "application log".

### ISSUE THREAD

**Issue by GitMensch** [ColinDuquesnoy/QCrash#5]
> > Hm, the full application for the current process isn't added to the issue, shouldn't it? You can see this in "review the report", too.
> 
> Yes. Only the last 100 lines are kept. A possible solution would be to upload the application log file as a gist.

Sounds like a plan, but it's exactly the log file that may contain sensitive data which I'd still like to be able to review [and change if necessary] before upload. To keep this options this should lead to a two-tab preview: the first one for the general data, the second (if activated) for the log.
The log could be uploaded as gist or send as mail attachment.

In any case one could select "don't include application log / include application log for current session / include complete application log" for making sure it isn't too big.

**Comment by ColinDuquesnoy** [comment]
Sounds good.

**Comment by ColinDuquesnoy** [comment]
Tested on linux (not integrated into OCIDE/HE yet).

**Comment by ColinDuquesnoy** [comment]
Now it has been integrated into OCIDE and tested under windows (see OpenCobolIDE/OpenCobolIDE#300 and OpenCobolIDE/OpenCobolIDE#301)
