### ISSUE TITLE
minor glitch: edit field positions in GitHub-Login

### ISSUE THREAD

**Issue by GitMensch** [ColinDuquesnoy/QCrash#7]
QCrash is so good that you can only find minor glitches already :-)

The edit fields for username and passwort differ in starting position by 1 pixel (zoom in to see it)

![qcrash-gh](https://cloud.githubusercontent.com/assets/6699539/14422163/903339c8-ffd5-11e5-92da-abcb2a488b1f.png)

**Comment by ColinDuquesnoy** [comment]
Nice catch! Should be fixed in next release.

**Comment by ColinDuquesnoy** [comment]
Should be fixed by using a form layout instead of two horizontal layouts.
