### ISSUE TITLE
Error message seems to be unescaped somewhere ("++" missing)

### ISSUE THREAD

**Issue by GitMensch** [ColinDuquesnoy/QCrash#9]
See https://github.com/OpenCobolIDE/OpenCobolIDE/issues/359.

The original error message was: 
`RuntimeError: wrapped C/C++ object of type CobolCodeEdit has been deleted"`

The error message copied to mail body was
`RuntimeError: wrapped C/C   object of type CobolCodeEdit has been deleted`

Not sure where the "++" where replaced by spaces.

**Comment by ColinDuquesnoy** [comment]
Not sure where this come from. Works fine for me: https://github.com/ColinDuquesnoy/QCrash-Test/issues/133

**Comment by GitMensch** [comment]
I think this issue occured when the message was copied _to_ the body field (not when typing manually in the body field).

**Comment by ColinDuquesnoy** [comment]
I've tried many things: typing, copying and raising an exception with the example message, everything works fine for me: https://github.com/ColinDuquesnoy/QCrash-Test/issues/139 (here I typed the title, pasted the description and did not change the traceback).
